param(
    [string]$Destination = "template/ecust-master-thesis",
    [string]$Source = "C:\Users\xiaoy\Desktop\ecust-master-thesis-latex-main",
    [string]$Repo = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$root = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")
if ([System.IO.Path]::IsPathRooted($Destination)) {
    $destPath = [System.IO.Path]::GetFullPath($Destination)
}
else {
    $destPath = [System.IO.Path]::GetFullPath((Join-Path $root $Destination))
}

if ((Test-Path -LiteralPath $destPath) -and -not $Force) {
    throw "Destination already exists: $destPath. Use -Force to replace it."
}

if (Test-Path -LiteralPath $destPath) {
    $resolved = Resolve-Path -LiteralPath $destPath
    $leaf = Split-Path -Leaf $resolved.Path
    $parent = Split-Path -Parent $resolved.Path
    $driveRoot = [System.IO.Path]::GetPathRoot($resolved.Path)
    $safeTemplateNames = @("template", "ecust-master-thesis")
    if (($resolved.Path -eq $driveRoot) -or [string]::IsNullOrWhiteSpace($parent) -or ($safeTemplateNames -notcontains $leaf)) {
        throw "Refusing to remove non-template path: $($resolved.Path)"
    }
    Remove-Item -LiteralPath $resolved.Path -Recurse -Force
}

$destParent = Split-Path -Parent $destPath
$destRoot = [System.IO.Path]::GetPathRoot($destPath)
if ((-not [string]::IsNullOrWhiteSpace($destParent)) -and ($destParent -ne $destRoot)) {
    New-Item -ItemType Directory -Force -Path $destParent | Out-Null
}
New-Item -ItemType Directory -Force -Path $destPath | Out-Null

if ($Source -and (Test-Path -LiteralPath $Source)) {
    Copy-Item -Path (Join-Path $Source "*") -Destination $destPath -Recurse -Force
    $sourceDescription = "Local standard template: $Source"
}
elseif ($Repo) {
    git clone --depth 1 $Repo $destPath
    $gitDir = Join-Path $destPath ".git"
    if (Test-Path -LiteralPath $gitDir) {
        Remove-Item -LiteralPath $gitDir -Recurse -Force
    }
    $sourceDescription = "Remote template source: $Repo"
}
else {
    throw "Cannot find local template source: $Source. Provide -Source or -Repo."
}

$tex = Join-Path $destPath "template.tex"
if (-not (Test-Path -LiteralPath $tex)) {
    throw "Cannot find template.tex in $destPath"
}

$content = Get-Content -LiteralPath $tex -Raw -Encoding UTF8

$replacements = [ordered]@{
    "论文题目" = "你的中文论文题目";
    "Your Thesis Title in English" = "Your English Thesis Title";
    "摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要摘要。" = "这里填写中文摘要。摘要应概括研究背景、研究问题、研究方法、主要结果和结论。";
    "关键词：}深度学习；xxx；xxx；xxx" = "关键词：}关键词一；关键词二；关键词三";
    "Abstract abstract abstract." = "Write the English abstract here.";
    "Keywords \ \ }Deep learning; xxx; xxx; xxx" = "Keywords \ \ }keyword one; keyword two; keyword three";
    "绪论绪论绪论绪论绪论绪论绪论绪论绪论绪论绪论绪论绪论绪论绪论绪论绪论。" = "本章介绍研究背景、研究意义、国内外研究现状、研究内容与方法以及论文结构。";
    "理论基础理论基础理论基础理论基础理论基础理\cite{lee2021mlcourse}论基础理论基础理论基础理论基础理论基础理论基础理论基础理论基础理论基础理论基础理论基础理论基础理论基础理论基础。" = "本章介绍研究所需的理论基础、核心概念和相关方法。";
    "XXX模型" = "研究方法与模型";
    "模型训练和改进" = "方法设计与实现";
    "此篇论文完稿之际，首先要感谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢致谢。" = "这里填写致谢内容。";
}

foreach ($key in $replacements.Keys) {
    $content = $content.Replace($key, $replacements[$key])
}

Set-Content -LiteralPath $tex -Value $content -Encoding UTF8

$notice = @"
# ECUST Template Source

This directory is generated by `scripts/prepare-ecust-template.ps1`.

Template source:

$sourceDescription

The script copies the standard template and rewrites placeholder text while keeping the format-oriented LaTeX structure.
Check your school's latest thesis requirements before final submission.
"@

Set-Content -LiteralPath (Join-Path $destPath "SOURCE.md") -Value $notice -Encoding UTF8

Write-Host "Prepared ECUST template at $destPath"
